# Generated by Django 4.1.13 on 2025-04-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_comment_blog_commen_created_0e6ed4_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='hoondori@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
